mongo:
  image: mongo:latest
  ports:
    - "27016:27016"
mysql:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=123456
  ports:
    - "3306:3306"
redis:
  image: redis
  ports:
    - "6379"
memcached:
  image: memcached
  ports:
    - "11211:11211"
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 5672:5672
    - 15672:15672
    # - 8080:8080
